remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Arexico Geofeed v1 (LEGACY)
description: A free and open geofeed for puplic IP resources. A project by Arexico and hosted by Github Pages.
markdown: kramdown
