remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Arexion Geofeed
description: A free and open geofeed for puplic IP resources. A project by Arexion and hosted by Github Pages.
markdown: kramdown
